In [1]:
import numpy as np
import torch

# Creating a tensor using PyTorch

In [3]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])
print(y)

tensor([[0.2390, 0.3432, 0.1639, 0.2748, 0.1589],
        [0.4732, 0.3535, 0.9235, 0.6412, 0.3223]])


# Reshaping a tensor or array

In [10]:
# Unlike reshape, we use view to reshape an arr
y = y.view([1,10])
y

tensor([[0.2390, 0.3432, 0.1639, 0.2748, 0.1589, 0.4732, 0.3535, 0.9235, 0.6412,
         0.3223]])