In [12]:
# Importing all necessary libraries
import numpy as np
import torch

# Creating a tensor using PyTorch

In [13]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [14]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [15]:
x.shape

torch.Size([2, 5])

In [16]:
y = torch.rand([2,5])
print(y)

tensor([[0.5646, 0.9034, 0.3102, 0.1657, 0.8065],
        [0.0940, 0.8772, 0.2911, 0.3702, 0.3391]])


# Reshaping a tensor or array

In [17]:
# Unlike reshape, we use view to reshape an array. Also, we need to reassign as the operation is not done inplace
y = y.view([1,10])
y

tensor([[0.5646, 0.9034, 0.3102, 0.1657, 0.8065, 0.0940, 0.8772, 0.2911, 0.3702,
         0.3391]])